### ISSUE TITLE
Question: license for project and Dockerfile

### ISSUE THREAD

**Issue by Richard-Strong** [ironPeakServices/iron-alpine#12]
Good day,

What is the license on this project, particularly the Dockerfile? I'd like to pull specific changes from your Dockerfile into my own project.

Thank you.

**Comment by hazcod** [comment]
Hi Richard, i’ll ad a license tonight, but feel free to reuse with a reference. PRs are welcome as wel!

**Comment by Richard-Strong** [comment]
@hazcod Thank you. So long as the license is permissive (i.e. "MIT"-like) I can definitely use the project (and possibly contribute).

**Comment by hazcod** [comment]
Fixed in https://github.com/ironPeakServices/iron-alpine/commit/96d1e6038b7b75443be90923b023742d43bfa4b6
