### ISSUE TITLE
Suggestion: publish more tags

### ISSUE THREAD

**Issue by frederikbosch** [ironPeakServices/iron-alpine#15]
Is there a specific reason why to only publish the exact version? I would suggest a tag `3.11` or even `3`.

**Comment by hazcod** [comment]
Hi frederik, mainly simplicity. I’ll implement  major versions this week.

**Comment by hazcod** [comment]
Since I'm using a GitHub Action for publishing to the Github registry, opening up https://github.com/elgohr/Publish-Docker-Github-Action/issues/67

**Comment by hazcod** [comment]
This is now implemented @frederikbosch

**Comment by frederikbosch** [comment]
Fantastic, thanks!
