### ISSUE TITLE
Question about post-install.sh

### ISSUE THREAD

**Issue by bcronrath** [ironPeakServices/iron-alpine#17]
I'm looking to build this container on my own without calling docker pull, and noticed the following lines at the end of the dockerfile:

    # add-in post installation file for permissions
    COPY post-install.sh $APP_DIR/
    RUN chmod 500 $APP_DIR/post-install.sh

It looks like there is some expectation to run the file afterward, I was wondering what the proper way to call this script is following the docker build?  I'm currently running into permissions when I just try to have it call the script following the docker build by running ./post-install.sh

**Comment by IAXES** [comment]
There's an `example` folder that imports IronAlpine as the baseline image, adds some more packages on top, and **then** runs `post-install.sh`. The reason (presumably) that the base-line image doesn't run this is that it's meant for downstream users of IronAlpine to execute it only after they've finished adding new packages to their IronAlpine-derived custom builds.

**Comment by hazcod** [comment]
Hi @bcronrath! The main goal of `post-install.sh` is 1) setting strict permissions after you are done installing and 2) removing the package managers once the container is finished.
```shell
#!/usr/bin/env sh

# fail if a command fails
set -e
set -o pipefail

# remove apk package manager
find / -type f -iname '*apk*' -xdev -delete
find / -type d -iname '*apk*' -print0 -xdev | xargs -0 rm -r --

# set rx to all directories, except data directory/
find "$APP_DIR" -type d -exec chmod 500 {} +

# set r to all files
find "$APP_DIR" -type f -exec chmod 400 {} +
chmod -R u=rwx "$DATA_DIR/"

# chown all app files
chown $APP_USER:$APP_USER -R $APP_DIR $DATA_DIR

# finally remove this file
rm "$0"
```

**Comment by bcronrath** [comment]
Thank you both for the information!
