### ISSUE TITLE
No new package released

### ISSUE THREAD

**Issue by frederikbosch** [ironpeakservices/iron-alpine#48]
Under [packages](https://github.com/orgs/ironpeakservices/packages?repo_name=iron-alpine) I only see 3.12.0, while the code suggests there should also be 3.13.1.

**Comment by hazcod** [comment]
I think this is because I try to generate a new semantic release instead of re-using the alpine version number.
And since those commits are prefixed with `chore`, it does not up the version. Fixing in https://github.com/ironpeakservices/iron-alpine/commit/35701f14fd7e60316eccb37e537fc904c3f68295

I might go back at re-using the alpine versioning tough.

**Comment by frederikbosch** [comment]
Wonderful, thanks, I am closing this one then

**Comment by hazcod** [comment]
FYI @frederikbosch I don't think it's quite fixed yet.

**Comment by frederikbosch** [comment]
Could you maybe have another look at this maybe @hazcod?

**Comment by frederikbosch** [comment]
It is not only the Docker version that is not published. Also, the git tag 3.13.2 still references alpine 3.12.2 in its [Dockerfile](https://github.com/ironpeakservices/iron-alpine/blob/v3.13.2/Dockerfile).

**Comment by hazcod** [comment]
Hi @frederikbosch , fixed!
```shell
% docker run -ti --rm ghcr.io/ironpeakservices/iron-alpine/iron-alpine:3.13.2 sh 
Unable to find image 'ghcr.io/ironpeakservices/iron-alpine/iron-alpine:3.13.2' locally
3.13.2: Pulling from ironpeakservices/iron-alpine/iron-alpine
ba3557a56b15: Already exists 
df3dbf292a15: Pull complete 
84e3d3d3af43: Pull complete 
d323597be315: Pull complete 
5663a11c8fbd: Pull complete 
23c849857221: Pull complete 
f60048fd2806: Pull complete 
11aea1149337: Pull complete 
0ae090df684d: Pull complete 
4e0dc1573991: Pull complete 
3eb3dbc13eb4: Pull complete 
9f60c3621e00: Pull complete 
0436fdf2f902: Pull complete 
7743f7cb0cea: Pull complete 
ef7b88c6b59d: Pull complete 
9ac28da2eeab: Pull complete 
9dfb7c0c70f9: Pull complete 
Digest: sha256:9d3ed556d4e5e2f231d55947ddbef6c305d9c3d94d9e4da95b1d3e268370021e
Status: Downloaded newer image for ghcr.io/ironpeakservices/iron-alpine/iron-alpine:3.13.2
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/app # cat /etc/alpine-release 
3.13.2
```

**Comment by frederikbosch** [comment]
Thanks for these fixes and merging the MRs. Hopefully we have a sustainable pipeline that can last for sometime!

**Comment by hazcod** [comment]
Thank you for the help @frederikbosch , really appreciate it.
